version: '3'

services:
  link-manager:
    container_name: link-manager
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4001:4000"
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:4001 # Change this to your domain in Portainer
      - NEXTAUTH_SECRET=changeme # Change this in Portainer
    volumes:
      - ./db:/app/db
